#define CAN_KICK 1
#define CAN_BAN 1
#define CAN_MISSIONCONTROL 1
#define CAN_USEDEBUGCONSOLE 1
#define CAN_DOACTIONS 1
#define CAN_SERVEREXEC 1
#define CAN_REMOTEEXEC 1
#define CAN_LOCALEXEC 1
#define CANNOT_KICK 0
#define CANNOT_BAN 0
#define CANNOT_MISSIONCONTROL 0
#define CANNOT_USEDEBUGCONSOLE 0
#define CANNOT_DOACTIONS 0
#define CANNOT_SERVEREXEC 0
#define CANNOT_REMOTEEXEC 0
#define CANNOT_LOCALEXEC 0


ids[] = {"76561198003012815"};
masks[] = {{CAN_KICK,CAN_BAN,CAN_MISSIONCONTROL,CAN_DOACTIONS,CAN_LOCALEXEC,CAN_REMOTEEXEC,CAN_SERVEREXEC,CAN_USEDEBUGCONSOLE}};
